- Numpy is a numerical python or number python

- its very helpful for all math operations

- representation of elements or number we can do following way

    - list

    - tuple

    - array

    - tensor

- list and tuple very base level representation

- whenever if any one say **array** means we need to recall **numpy**

- whenever if any one **tensor** means we need to recall **tensorflow and pytorch**

- numpy arrays are having shape and dimensions

- numpy arrays and tensors are similar in nature

- if we use cpu then numpy is best

- if we use gpu then tensors are best

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
import sys

In [4]:
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

In [5]:
import pandas as pd

In [6]:
pd.__version__

'2.2.3'

**create an array**

In [8]:
l=[1,2,3]
l

[1, 2, 3]

In [9]:
np.array(l)

array([1, 2, 3])

**why numpy arrays are famous**

In [19]:
l1=[10,20,30,40]
l2=[100,200,300,400]
l=[]
#l=[110,220,330,440]
for i,j in zip(l1,l2):
    l.append(i+j)
l

[110, 220, 330, 440]

In [21]:
l=[i+j for i,j in zip(l1,l2)]
l

[110, 220, 330, 440]

In [22]:
arr1=np.array(l1)
arr2=np.array(l2)
arr1,arr2

(array([10, 20, 30, 40]), array([100, 200, 300, 400]))

In [23]:
arr1+arr2

array([110, 220, 330, 440])

In [24]:
arr1*arr2

array([ 1000,  4000,  9000, 16000])

In [25]:
arr1/arr2

array([0.1, 0.1, 0.1, 0.1])

In [26]:
arr1-arr2

array([ -90, -180, -270, -360])

**speed test**

In [28]:
import time
start=time.time()
l1=list(range(1,10000000))
l2=list(range(1,10000000))
l=[i*j for i,j in zip(l1,l2)]
end=time.time()
print(f'total time taken is:{end-start}')

total time taken is:2.0164644718170166


In [30]:
import time
start=time.time()
arr1=np.arange(1,10000000)
arr2=np.arange(1,10000000)
end=time.time()
print(f'total time taken is:{end-start}')


total time taken is:0.07186222076416016
